# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 7, 47, 10, 633652, tzinfo=utc)),
        ),
    ]
