# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170524_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_img',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
